name: Monkey Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: ls
      run: ls

    - name: Go to GOROOT directory
      run: cd monkey/
    
    - name: ls2
      run: ls

    - name: Test Lexer
      run: go test ./lexer/
    
    - name: Test Parser
      run: go test ./parser/
    
